name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '5.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code 
        uses: actions/checkout@v2

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
    
      - name: Restore Dependencies
        run: dotnet restore

      - name: Build App
        run: dotnet build -c Release --no-restore